[project]
name = "transmission_bot"
version = "0.1.0"
description = "transmission_bot"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "python-telegram-bot>=22.0",
    "transmission-rpc>=7.0.11",
]
